apiVersion: apps/v1
kind: Deployment
metadata:
  name: sql-server
spec:
  selector:
    matchLabels:
      app: sql-server
  template:
    metadata:
      labels:
        app: sql-server
    spec:
      containers:
      - name: sql-server
        image: mcr.microsoft.com/mssql/server:2022-latest
        env:
          - name: ACCEPT_EULA
            value: "Y"
          - name: "SA_PASSWORD"
            value: "TokyoJoe138!"
        resources:
          limits:
            memory: "2048Mi"
            cpu: "500m"
        ports:
        - containerPort: 1433
