apiVersion: apps/v1
kind: Deployment
metadata:
  name: playlists-api
spec:
  selector:
    matchLabels:
      app: playlists-api
  template:
    metadata:
      labels:
        app: playlists-api
    spec:
      containers:
      - name: playlists-api
        image: playlists-api:v0.1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
